OA.UIPortal/Models/LoginVerifyFilterAttribute.cs
using OA.Commom.Cache;
using OA.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OA.UIPortal.Models
{
    public class LoginVerifyFilterAttribute : ActionFilterAttribute
    {
        public bool IsCheck { get; set; }
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            if (IsCheck)
            {
                if (filterContext.HttpContext.Request.Cookies["userLoginId"] == null)
                {
                    filterContext.HttpContext.Response.Redirect("/UserLogin/Index");
                    return;
                }
                string userLoginId = filterContext.HttpContext.Request.Cookies["userLoginId"].Value;
                UserInfo loginUser = CacheHelper.GetCache(userLoginId) as UserInfo;
                if (loginUser == null)
                {
                    filterContext.HttpContext.Response.Redirect("/UserLogin/Index");
                    return;
                }
                else
                {
                    CacheHelper.SetCache(userLoginId, loginUser, DateTime.Now.AddMinutes(20));
                }
            }
        }
    }
}

OA.UIPortal/Models/MyExceptionFilterAttribute.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OA.UIPortal.Models
{
    public class MyExceptionFilterAttribute : HandleErrorAttribute
    {
        public override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            Commom.LogHelper.WriteLog(filterContext.Exception.ToString());
        }
    }
}

OA.UIPortal/Models/MyLoginVerifyFilterAttribute.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OA.UIPortal.Models
{
    public class MyLoginVerifyFilterAttribute:ActionFilterAttribute
    {
        public bool IsCheck { get; set; }
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            if (IsCheck)
            {
                if (filterContext.HttpContext.Session["loginUser"] == null)
                {
                    filterContext.HttpContext.Response.Redirect("/UserLogin/Index");
                }
            }
        }
    }
}

OA.UIPortal/Controllers/UserInfoController.cs
using OA.BLL;
using OA.Commom.Cache;
using OA.IBLL;
using OA.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OA.UIPortal.Controllers
{
    public class UserInfoController : Controller
    {
        IUserInfoService UserInfoService { get; set; }
        //
        // GET: /UserInfo/

        public ActionResult Index()
        {
            //throw new Exception("出错啦");
            string aa=CacheHelper.GetCache("verifyCode").ToString();
            ViewData.Model = UserInfoService.GetEntities(u=>true);
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(UserInfo userInfo)
        {
            if (ModelState.IsValid)
            {
                UserInfoService.Add(userInfo);
            }
            return RedirectToAction("Index");
        }
        public ActionResult Test()
        {
            return View();
        }

        public ActionResult Delete(int ID)
        {
            UserInfoService.Delete(ID);
            return RedirectToAction("Index");
        }
    }
}

OA.UIPortal/Controllers/UserLoginController.cs
using Memcached.ClientLibrary;
using OA.BLL;
using OA.Commom.Cache;
using OA.Commom.tools;
using OA.IBLL;
using OA.Model;
using OA.UIPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OA.Commom.ParamModel;

namespace OA.UIPortal.Controllers
{
    [LoginVerifyFilter(IsCheck = false)]
    public class UserLoginController : Controller
    {
       
        private IUserInfoService UserInfoService { get; set; }
        //
        // GET: /UserLogin/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProcessLogin(string UserName,string Password,string VerifyCode)
        {
            string verifyCode = CacheHelper.GetCache("verifyCode").ToString();
            if (verifyCode == VerifyCode)
            {
                UserInfo loginUser = UserInfoService.GetEntities(u => u.Name == UserName).FirstOrDefault();
                if (loginUser != null && loginUser.Password == Password)
                {
                    string userLoginId = Guid.NewGuid().ToString();
                    Response.Cookies["userLoginId"].Value = userLoginId;
                    CacheHelper.AddCache(userLoginId, loginUser, DateTime.Now.AddMinutes(20));
                    //Session["loginUser"] = loginUser;
                    return Content("succeed");
                }
                else
                {
                    return Content("failed");
                }
            }
            else
            {
                return Content("verifyCodeError");
            }
        }
        //获取验证码
        public ActionResult GetAuthCode()
        {
            VerifyCode verifyCode = new VerifyCode();
            byte[] data = verifyCode.GetVerifyCode(new VerifyCodeParam());
            return File(data, @"image/png");
        }
    } 
}

OA.UIPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
   @* @Styles.Render("~/Content/css")*@
   @* @Scripts.Render("~/bundles/modernizr")*@
    <link href="~/Content//Blue/layui/css/layui.css" rel="stylesheet" />
    <link href="~/Content/Blue/CSS/common.css" rel="stylesheet" />
    <link href="~/Content/Blue/CSS/init.css" rel="stylesheet" />
    <link href="~/Content/Blue/CSS/template.css" rel="stylesheet" />
    <script src="~/Content/Blue/layui/layui.js"></script>
    <script src="~/Content/Blue/jquery-3.3.1/jquery-3.3.1.min.js"></script>
    <script src="~/Content/Blue/JS/common.js"></script>
</head>
<body>
      <div id="top">
        <div class="layui-carousel" id="carouel">
            <div carousel-item><!--轮播图-->
                <img src="~/Content/Blue/Images/22.jpg" />
                <img src="~/Content/Blue/Images/22.jpg" />
            </div>       
        </div>
        <ul class="layui-nav body-top-ul">
          <li class="layui-nav-item">
            <a href="" id="a-loginUserName" style="color:#fff;pointer-events:none"></a><!--欢迎+用户名-->
          </li>
          <li class="layui-nav-item">
             <select name="userName" id="roleSelect" lay-verify="required" lay-search class="body-select-role"><!--下拉更改角色-->

              </select>
          </li>
          <li class="layui-nav-item">
            <a href="Login.html" style="color:#fff" id="a-logout">注销</a><!--注销-->
          </li>
        </ul>
    </div>
    <ul class="layui-nav layui-nav-tree layui-nav-side ul-top" id="ul-nav">
    </ul>
    @*<iframe id="changeIframe" src="Main.html" class="iframe"></iframe>*@
    <script src="~/Content/Blue/JS/template.js"></script>
    <div  class="iframe">
    @RenderBody()
    </div>
   @* @Scripts.Render("~/bundles/jquery")*@
    @RenderSection("scripts", required: false)
</body>
</html>

OA.UIPortal/Views/UserInfo/Create.cshtml
@model OA.Model.UserInfo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Scripts.Render("~/Scripts/jquery-1.8.2.min.js")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js")
}

<h2>Create</h2>

@using(Html.BeginForm("Create","UserInfo",new AjaxOptions(){})) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>UserInfo</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SubTime)
            @Html.ValidationMessageFor(model => model.SubTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ModifiedOn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ModifiedOn)
            @Html.ValidationMessageFor(model => model.ModifiedOn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Remark)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Remark)
            @Html.ValidationMessageFor(model => model.Remark)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DelFlag)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DelFlag)
            @Html.ValidationMessageFor(model => model.DelFlag)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OA.UIPortal/Views/UserInfo/Index.cshtml
@model IEnumerable<OA.Model.UserInfo>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div>
        <div class="layui-btn-group" id="toolbar">
             @Html.ActionLink("增加", "Create", "UserInfo", new {@class="layui-btn" ,@id="addUserInfo" })
             @Html.ActionLink("删除", "Delete", "UserInfo", new {@class="layui-btn" ,@id="deleteUserInfo" })
            <button type="button" class="layui-btn" id="upload">
                <i class="layui-icon">&#xe67c;</i>上传图片
            </button>
        </div>

        <table id="userInfoTable" lay-filter="userInfo" class="layui-table">
            @foreach (var item in Model) { 
                <tr>
                    <td>@Html.DisplayFor(uName=>item.Name)</td>
                    <td>@Html.DisplayFor(uPassword=>item.Password)</td>
                    <td>@Html.DisplayFor(uDelflag=>item.DelFlag)</td>
                    <td>
                        <div class="layui-btn-group" id="toolbar-tr">
                            @Html.ActionLink("编辑", "Edit", "UserInfo",new {id=item.ID}, new {@class="layui-btn common-tr-btn-height" }) 
                            @Html.ActionLink("删除", "Delete", "UserInfo",new {id=item.ID}, new {@class="layui-btn common-tr-btn-height"  }) 
                            @Html.ActionLink("详情", "Details", "UserInfo", new { id = item.ID }, new {@class="layui-btn common-tr-btn-height" })
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>
    <script src="../Blue/JS/UserInfoManage.js"></script>

OA.UIPortal/Views/UserInfo/Test.cshtml
{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test</h2>

OA.UIPortal/Views/UserLogin/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <link href="../Content/Blue/layui/css/layui.css" rel="stylesheet" />
    <link href="../Content/Blue/CSS/login.css" rel="stylesheet" />
    <link href="../Content/Blue/CSS/common.css" rel="stylesheet" />
    <link href="../Content/Blue/CSS/init.css" rel="stylesheet" />
    <script src="../Content/Blue/layui/layui.js"></script>
    @*<script src="../Content/Blue/JS/login.js"></script>*@
    <script src="../Content/Blue/jquery-3.3.1/jquery-3.3.1.min.js"></script>
    <script src="../Content/Blue/JS/common.js"></script>
    <script>
        function loginSuccess(data) {
            if (data == "succeed") {
                window.location.href = "/UserInfo/Index";
            } else if (data == "failed") {
                alert("登录失败");
            } else if (data == "verifyCodeError") {
                alert("验证码错误");
            }
        }
        function reImg() {
            var img = document.getElementById("imgcode");
            img.src = "/UserLogin/GetAuthCode?time=" + Math.random();
        }
    </script>
</head>
<body class="body">
    @using (Ajax.BeginForm("ProcessLogin", "UserLogin", new AjaxOptions()
    {
        OnSuccess = "loginSuccess"
    }))
    {
        <div class="layui-main main">
            <form class="layui-form form">
                <div class="layui-form-item">
                    @Html.Label("用户名", new { @class = "layui-form-label font-aligin-left" })
                    <div class="layui-input-block">
                       @* <input type="text" name="userName" required lay-verify="required" placeholder="请输入用户名" autocomplete="off" class="layui-input" />*@
                        @Html.TextBox("UserName", "", new { @name = "UserName",@placeholder="请输入用户名",@class="layui-input",@autocomplete="off"})
                    </div>
                </div>
                <div class="layui-form-item">
                    @Html.Label("密码", new { @class = "layui-form-label font-aligin-left" })
                    <div class="layui-input-block">
                       @* <input type="text" name="password" required lay-verify="required" placeholder="请输入密码" autocomplete="off" class="layui-input" />*@
                        @Html.TextBox("Password", "", new { @name = "Password", @placeholder = "请输入密码", @autocomplete = "off", @class = "layui-input" })
                    </div>
                </div>
                <div class="layui-form-item">
                <div class="layui-input-block">
                     @Html.TextBox("VerifyCode", "", new { @name = "VerifyCode",@placeholder="请输入验证码",@class="layui-input",@autocomplete="off"})
                    <div style="width: 110px; float: right; padding-top: 14px; padding-left: 14px;">
                            看不清？<a id="switchCode" href="#;" onclick="reImg()" style="text-decoration: none;">换一张</a>
                            <img id="imgcode" class="authcode" src="~/UserLogin/GetAuthCode" width=" 80" height="25" />
                    </div>
                </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button class="layui-btn btn-login-register-color" lay-submit lay-filter="formDemo">登录</button>
                        <button class="layui-btn btn-login-register-color">注册</button>
                    </div>
                </div>
            </form>
        </div>
    }
</body>
</html>